# Generated by Django 6.0.5 on 2026-06-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_stock_remove_variation_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
