# Generated by Django 6.0.5 on 2026-08-03 08:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_attribute_remove_productconfiguration_variations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productconfiguration',
            name='configuration_signature',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='productconfiguration',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='productconfiguration',
            unique_together={('product', 'configuration_signature')},
        ),
    ]
