# Generated by Django 6.0.5 on 2026-06-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='active',
            new_name='is_active',
        ),
    ]
