# Generated by Django 6.0.5 on 2026-07-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_remove_cartitem_variations'),
        ('store', '0008_attribute_remove_productconfiguration_variations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, to='store.attributevalue'),
        ),
    ]
