# Generated by Django 6.0.5 on 2026-06-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
