# Generated by Django 6.0.5 on 2026-06-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
