# Generated by Django 6.0.5 on 2026-07-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderproduct_attribute_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='usd_amount',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
